In [1]:
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action="ignore", category=FutureWarning)

In [2]:
from utils import setup
from indicators import  compute_indicators

In [3]:
#surrogate model
from utils import set_model
surrogate_model = set_model("Gowal2021Improving_R18_ddpm_100m","cifar10","Linf")

In [4]:
attack,model,dataloader = setup(num_samples=1,
                                n_batches=1,
                                num_steps=5,
                                step_size=4/255,
                                epsilon=8/255,
                                model="Pang2022Robustness_WRN28_10",
                                dataset_name="cifar10",
                                threat_model="Linf"
                                )
ds = compute_indicators(attack,model,dataloader,surrogate_model)
ds

Downloading models\cifar10\Linf\Pang2022Robustness_WRN28_10.pt (gdrive_id=16ChNkterCp17BXv-xxqpfedb4u2_CjjS).

Downloading...
From (original): https://drive.google.com/uc?id=16ChNkterCp17BXv-xxqpfedb4u2_CjjS
From (redirected): https://drive.google.com/uc?id=16ChNkterCp17BXv-xxqpfedb4u2_CjjS&confirm=t&uuid=2b243202-6bd1-4e1e-8680-6dc187660171
To: C:\Users\ropin\PycharmProjects\SecML_pjV3\models\cifar10\Linf\Pang2022Robustness_WRN28_10.pt
100%|██████████| 146M/146M [00:40<00:00, 3.59MB/s]

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

start transfer_failure_indicator..
end transfer_failure_indicator

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,1.0,False,0.002512,False,1.0,0.0,0.0

In [5]:
attack,model,dataloader = setup(num_samples=20,
                                n_batches=2,
                                num_steps=5,
                                step_size=4/255,
                                epsilon=8/255,
                                model="Pang2022Robustness_WRN28_10",
                                dataset_name="cifar10",
                                threat_model="Linf")
ds = compute_indicators(attack,model,dataloader,surrogate_model)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

start transfer_failure_indicator..
end transfer_failure_indicator

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,0.8,False,0.008412,False,1.0,0.15,0.45

In [6]:
attack, model, dataloader = setup(num_samples=1,
                                  n_batches=1,
                                  num_steps=50,
                                  step_size=4 / 255,
                                  epsilon=8 / 255,
                                  model="Pang2022Robustness_WRN28_10",
                                  dataset_name="cifar10",
                                  threat_model="Linf")
ds = compute_indicators(attack,model,dataloader,surrogate_model)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

start transfer_failure_indicator..
end transfer_failure_indicator

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,1.0,False,0.003052,False,0.0,0.0,0.0

In [7]:
attack,model,dataloader = setup(num_samples=20,
                                n_batches=2,
                                num_steps=50,
                                step_size=4/255,
                                epsilon=8/255,
                                model="Pang2022Robustness_WRN28_10",
                                dataset_name="cifar10",
                                threat_model="Linf")
ds = compute_indicators(attack,model,dataloader,surrogate_model)
ds

starting pre-processing...
end pre-processing

obtaining trackers...
trackers obtained

starting unavailable_gradients_indicator...
end unavailable_gradients_indicator

staring unstable_predictions_indicator...
end unstable_predictions_indicator

staring silent_success_indicator...
end silent_success_indicator

starting incomplete_optimization_indicator...
end incomplete_optimization_indicator

start transfer_failure_indicator..
end transfer_failure_indicator

starting unconstrained_attack_failure_indicator..
end unconstrained_attack_failure_indicator

starting Attack_fails...
end Attack_fails

,attack_fails,unavailable_gradients,unstable_predictions,silent_success,incomplete_optimization,transfer_failure,unconstrained_attack_failure
0,0.75,False,0.007706,False,0.0,0.1,0.0